title: "Shuban CSA"
description: "Shuban's Computer Science A Portfolio"
owner_name: Shuban Pal
github_username: shuban-789
github_repo: "Shuban-CSA" 
baseurl: "/Shuban-CSA"
future: true
url: "https://shuban-789.github.io/Shuban-CSA/"
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/shuban-789" }
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 
# remote_theme: pages-themes/midnight@v0.2.0
remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/blog.md
  - navigation/search.md
  - navigation/about.md
  - README4YML.md
